#' Generate an interactive HERVariumR dashboard
#'
#' Generates an HTML dashboard from either a HERVarium_annotation or
#' HERVarium_comparison object.
#'
#' @param x A HERVarium_annotation or HERVarium_comparison object.
#' @param output_dir Output directory.
#' @param report_file Name of the HTML report.
#' @param title Report title.
#' @param top_n Number of top features to show in dashboard plots.
#' @param self_contained Whether to produce a self-contained HTML file.
#'
#' @return Invisibly returns the path to the generated HTML dashboard.
#' @export

generate_hervarium_dashboard <- function(x,
                                         output_dir = NULL,
                                         report_file = NULL,
                                         title = NULL,
                                         top_n = 25,
                                         self_contained = TRUE) {
  
  if (!requireNamespace("rmarkdown", quietly = TRUE)) {
    stop("Package 'rmarkdown' is required. Install it with install.packages('rmarkdown').")
  }
  
  if (!requireNamespace("DT", quietly = TRUE)) {
    stop("Package 'DT' is required. Install it with install.packages('DT').")
  }
  
  if (!requireNamespace("plotly", quietly = TRUE)) {
    stop("Package 'plotly' is required. Install it with install.packages('plotly').")
  }
  
  if (!requireNamespace("ggplot2", quietly = TRUE)) {
    stop("Package 'ggplot2' is required. Install it with install.packages('ggplot2').")
  }
  
  if (!inherits(x, "HERVarium_comparison") &&
      !inherits(x, "HERVarium_annotation")) {
    stop("x must be a HERVarium_comparison or HERVarium_annotation object.")
  }
  
  if (is.null(output_dir)) {
    output_dir <- x$output_dir
  }
  
  if (is.null(output_dir)) {
    stop("Please provide output_dir or use an object with output_dir.")
  }
  
  if (!dir.exists(output_dir)) {
    dir.create(output_dir, recursive = TRUE)
  }
  
  object_type <- if (inherits(x, "HERVarium_comparison")) {
    "comparison"
  } else {
    "annotation"
  }
  
  if (is.null(report_file)) {
    report_file <- if (object_type == "comparison") {
      "hervarium_comparison_dashboard.html"
    } else {
      "hervarium_annotation_dashboard.html"
    }
  }
  
  if (is.null(title)) {
    title <- if (object_type == "comparison") {
      paste0("HERVariumR comparison dashboard: ",
             x$foreground_name, " vs ", x$background_name)
    } else {
      "HERVariumR annotation dashboard"
    }
  }
  
  object_rds <- file.path(output_dir, "hervarium_dashboard_object.rds")
  rmd_file <- file.path(output_dir, "hervarium_dashboard.Rmd")
  
  saveRDS(x, object_rds)
  
  if (object_type == "comparison") {
    write_hervarium_comparison_dashboard_rmd(
      rmd_file = rmd_file,
      title = title,
      top_n = top_n,
      self_contained = self_contained
    )
  } else {
    write_hervarium_annotation_dashboard_rmd(
      rmd_file = rmd_file,
      title = title,
      top_n = top_n,
      self_contained = self_contained
    )
  }
  
  old_wd <- getwd()
  on.exit(setwd(old_wd), add = TRUE)
  setwd(output_dir)
  
  rmarkdown::render(
    input = basename(rmd_file),
    output_file = report_file,
    quiet = TRUE,
    envir = new.env(parent = globalenv())
  )
  
  message("HERVariumR dashboard written to: ", file.path(output_dir, report_file))
  
  invisible(file.path(output_dir, report_file))
}


write_hervarium_comparison_dashboard_rmd <- function(rmd_file,
                                                     title,
                                                     top_n = 25,
                                                     self_contained = TRUE) {
  
  self_contained_txt <- ifelse(self_contained, "true", "false")
  
  rmd_text <- c(
    "---",
    paste0("title: \"", title, "\""),
    "output:",
    "  html_document:",
    "    toc: true",
    "    toc_float: true",
    "    theme: flatly",
    paste0("    self_contained: ", self_contained_txt),
    "---",
    "",
    "```{r setup, include=FALSE}",
    "knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)",
    "library(ggplot2)",
    "library(plotly)",
    "library(DT)",
    "",
    "cmp <- readRDS('hervarium_dashboard_object.rds')",
    "features <- cmp$features",
    "top_n <- ", as.character(top_n),
    "",
    "domain_coverage_cutoff <- NA_real_",
    "",
    "if (!is.null(cmp$annotation) &&",
    "    !is.null(cmp$annotation$stats) &&",
    "    'domain_coverage_cutoff' %in% colnames(cmp$annotation$stats)) {",
    "  domain_coverage_cutoff <- cmp$annotation$stats$domain_coverage_cutoff[1]",
    "}",
    "",
    "if (is.na(domain_coverage_cutoff) &&",
    "    !is.null(cmp$domain_coverage_cutoff)) {",
    "  domain_coverage_cutoff <- cmp$domain_coverage_cutoff",
    "}",
    "",
    "domain_threshold_text <- ifelse(",
    "  is.na(domain_coverage_cutoff),",
    "  'No domain coverage threshold was found in the object. Domain summaries reflect the domain annotations stored in the input object.',",
    "  paste0(",
    "    'Internal retroviral domains were considered valid only when HMM profile coverage was >= ',",
    "    domain_coverage_cutoff,",
    "    '. Domain counts, domain-class presence, domain-type enrichment and conservation plots are based on this threshold.'",
    "  )",
    ")",
    "",
    "safe_dt <- function(x, page_length = 10) {",
    "  if (is.null(x) || nrow(x) == 0) {",
    "    return(htmltools::HTML('<p><em>No results available for this section.</em></p>'))",
    "  }",
    "  DT::datatable(",
    "    x,",
    "    filter = 'top',",
    "    extensions = c('Buttons'),",
    "    options = list(",
    "      pageLength = page_length,",
    "      scrollX = TRUE,",
    "      dom = 'Bfrtip',",
    "      buttons = c('copy', 'csv', 'excel')",
    "    )",
    "  )",
    "}",
    "",
    "safe_neglog10 <- function(p) {",
    "  p <- suppressWarnings(as.numeric(p))",
    "  p[p == 0] <- .Machine$double.xmin",
    "  -log10(p)",
    "}",
    "",
    "add_plot_log2_or <- function(df, pseudocount = 0.5) {",
    "  if (is.null(df) || nrow(df) == 0) return(df)",
    "  count_cols <- c('foreground_yes', 'foreground_no', 'background_yes', 'background_no')",
    "  if (all(count_cols %in% colnames(df))) {",
    "    a <- df$foreground_yes + pseudocount",
    "    b <- df$foreground_no + pseudocount",
    "    c <- df$background_yes + pseudocount",
    "    d <- df$background_no + pseudocount",
    "    df$odds_ratio_plot <- (a / b) / (c / d)",
    "    df$log2_or_plot <- log2(df$odds_ratio_plot)",
    "  } else {",
    "    df$log2_or_plot <- suppressWarnings(log2(df$odds_ratio))",
    "    df$log2_or_plot[is.infinite(df$log2_or_plot)] <- NA_real_",
    "  }",
    "  df",
    "}",
    "",
    "comparison_palette <- c(",
    "  'Significant enriched' = '#D55E00',",
    "  'Significant depleted' = '#0072B2',",
    "  'Not significant' = '#BDBDBD'",
    ")",
    "",
    "add_effect_category <- function(df, effect_col, padj_cutoff = 0.05) {",
    "  df$effect_category <- 'Not significant'",
    "  sig <- !is.na(df$padj) & df$padj < padj_cutoff",
    "  enriched <- !is.na(df[[effect_col]]) & df[[effect_col]] > 0",
    "  depleted <- !is.na(df[[effect_col]]) & df[[effect_col]] < 0",
    "  df$effect_category[sig & enriched] <- 'Significant enriched'",
    "  df$effect_category[sig & depleted] <- 'Significant depleted'",
    "  df$effect_category <- factor(",
    "    df$effect_category,",
    "    levels = c(",
    "      'Significant enriched',",
    "      'Significant depleted',",
    "      'Not significant'",
    "    )",
    "  )",
    "  df",
    "}",
    "",
    "plot_enrichment <- function(df, title, top_n = 25, padj_cutoff = 0.05) {",
    "  if (is.null(df) || nrow(df) == 0) return(NULL)",
    "  df <- df[!is.na(df$p_value), , drop = FALSE]",
    "  if (nrow(df) == 0) return(NULL)",
    "  df <- add_plot_log2_or(df)",
    "  df <- add_effect_category(df, effect_col = 'log2_or_plot', padj_cutoff = padj_cutoff)",
    "  df <- df[order(df$p_value), , drop = FALSE]",
    "  df <- head(df, top_n)",
    "  df$feature <- factor(df$feature, levels = rev(df$feature))",
    "  p <- ggplot(df, aes(x = feature, y = log2_or_plot, fill = effect_category,",
    "                     text = paste0(",
    "                       'Feature: ', feature,",
    "                       '<br>Direction: ', effect_category,",
    "                       '<br>Foreground: ', foreground_yes, '/', foreground_total,",
    "                       ' (', round(foreground_percent, 1), '%)',",
    "                       '<br>Background: ', background_yes, '/', background_total,",
    "                       ' (', round(background_percent, 1), '%)',",
    "                       '<br>OR: ', round(odds_ratio, 3),",
    "                       '<br>Plot log2 OR: ', round(log2_or_plot, 3),",
    "                       '<br>p-value: ', signif(p_value, 3),",
    "                       '<br>FDR: ', signif(padj, 3)",
    "                     ))) +",
    "    geom_col() +",
    "    coord_flip() +",
    "    geom_hline(yintercept = 0, linetype = 'dashed') +",
    "    scale_fill_manual(values = comparison_palette, drop = FALSE) +",
    "    labs(title = title, x = NULL, y = 'log2 odds ratio', fill = NULL) +",
    "    theme_bw() +",
    "    theme(legend.position = 'top')",
    "  plotly::ggplotly(p, tooltip = 'text')",
    "}",
    "",
    "plot_numeric <- function(df, title, top_n = 25, padj_cutoff = 0.05) {",
    "  if (is.null(df) || nrow(df) == 0) return(NULL)",
    "  df <- df[!is.na(df$p_value), , drop = FALSE]",
    "  if (nrow(df) == 0) return(NULL)",
    "  df <- add_effect_category(df, effect_col = 'delta_median', padj_cutoff = padj_cutoff)",
    "  df <- df[order(df$p_value), , drop = FALSE]",
    "  df <- head(df, top_n)",
    "  df$feature <- factor(df$feature, levels = rev(df$feature))",
    "  p <- ggplot(df, aes(x = feature, y = delta_median, fill = effect_category,",
    "                     text = paste0(",
    "                       'Feature: ', feature,",
    "                       '<br>Direction: ', effect_category,",
    "                       '<br>Foreground median: ', round(foreground_median, 3),",
    "                       '<br>Background median: ', round(background_median, 3),",
    "                       '<br>Delta median: ', round(delta_median, 3),",
    "                       '<br>p-value: ', signif(p_value, 3),",
    "                       '<br>FDR: ', signif(padj, 3)",
    "                     ))) +",
    "    geom_col() +",
    "    coord_flip() +",
    "    geom_hline(yintercept = 0, linetype = 'dashed') +",
    "    scale_fill_manual(values = comparison_palette, drop = FALSE) +",
    "    labs(title = title, x = NULL, y = 'Delta median', fill = NULL) +",
    "    theme_bw() +",
    "    theme(legend.position = 'top')",
    "  plotly::ggplotly(p, tooltip = 'text')",
    "}",
    "```",
    "",
    "# Overview",
    "",
    "## Analysis settings",
    "",
    "```{r analysis-settings}",
    "htmltools::div(",
    "  style = 'padding: 12px; border-left: 5px solid #0072B2; background-color: #F2F7FB; margin-bottom: 15px;',",
    "  htmltools::strong('Domain coverage threshold: '),",
    "  htmltools::HTML(domain_threshold_text)",
    ")",
    "```",
    "",
    "## Input summary",
    "",
    "```{r input-summary}",
    "safe_dt(cmp$input_summary, page_length = 5)",
    "```",
    "",
    "## Matched HERV features",
    "",
    "```{r features-table}",
    "safe_dt(features, page_length = 10)",
    "```",
    "",
    "# Core enrichment",
    "",
    "## Binary feature enrichment",
    "",
    "```{r binary-feature-plot}",
    "plot_enrichment(cmp$binary_features, 'Binary feature enrichment', top_n = 50, padj_cutoff = 0.05)",
    "```",
    "",
    "```{r binary-feature-table}",
    "safe_dt(cmp$binary_features, page_length = 15)",
    "```",
    "",
    "## Numeric feature shifts",
    "",
    "```{r numeric-feature-plot}",
    "plot_numeric(cmp$numeric_features, 'Numeric feature shifts', top_n = top_n, padj_cutoff = 0.05)",
    "```",
    "",
    "```{r numeric-feature-table}",
    "safe_dt(cmp$numeric_features, page_length = 15)",
    "```",
    "",
    "# HERV identity and domains",
    "",
    "## Subfamily enrichment",
    "",
    "```{r subfamily-plot}",
    "plot_enrichment(cmp$subfamily_enrichment, 'Subfamily enrichment', top_n = top_n, padj_cutoff = 0.05)",
    "```",
    "",
    "```{r subfamily-table}",
    "safe_dt(cmp$subfamily_enrichment, page_length = 15)",
    "```",
    "",
    "## Domain type enrichment",
    "",
    "```{r domain-type-plot}",
    "plot_enrichment(cmp$domain_type_enrichment, 'Internal domain type enrichment', top_n = top_n, padj_cutoff = 0.05)",
    "```",
    "",
    "```{r domain-type-table}",
    "safe_dt(cmp$domain_type_enrichment, page_length = 15)",
    "```",
    "",
    "# Regulatory layers",
    "",
    "## IFN/LTR curated features",
    "",
    "```{r ifn-plot}",
    "plot_enrichment(cmp$ifn_ltr_features, 'IFN-related LTR feature enrichment', top_n = 50, padj_cutoff = 0.05)",
    "```",
    "",
    "```{r ifn-table}",
    "safe_dt(cmp$ifn_ltr_features, page_length = 15)",
    "```",
    "",
    "## LTR TFBM burden",
    "",
    "```{r ltr-burden-plot}",
    "plot_numeric(cmp$ltr_tfbm_burden, 'LTR TFBM burden comparison', top_n = 10, padj_cutoff = 0.05)",
    "```",
    "",
    "```{r ltr-burden-table}",
    "safe_dt(cmp$ltr_tfbm_burden, page_length = 10)",
    "```",
    "",
    "## 5' LTR TFBM motif enrichment",
    "",
    "```{r ltr5-tfbm-plot}",
    "plot_enrichment(cmp$ltr5_tfbm_motif_enrichment, '5' LTR TFBM motif enrichment', top_n = top_n, padj_cutoff = 0.05)",
    "```",
    "",
    "```{r ltr5-tfbm-table}",
    "safe_dt(cmp$ltr5_tfbm_motif_enrichment, page_length = 15)",
    "```",
    "",
    "## 3' LTR TFBM motif enrichment",
    "",
    "```{r ltr3-tfbm-plot}",
    "plot_enrichment(cmp$ltr3_tfbm_motif_enrichment, '3' LTR TFBM motif enrichment', top_n = top_n, padj_cutoff = 0.05)",
    "```",
    "",
    "```{r ltr3-tfbm-table}",
    "safe_dt(cmp$ltr3_tfbm_motif_enrichment, page_length = 15)",
    "```",
    "",
    "## Any-LTR TFBM motif enrichment",
    "",
    "```{r any-ltr-tfbm-plot}",
    "plot_enrichment(cmp$any_ltr_tfbm_motif_enrichment, 'Any-LTR TFBM motif enrichment', top_n = top_n, padj_cutoff = 0.05)",
    "```",
    "",
    "```{r any-ltr-tfbm-table}",
    "safe_dt(cmp$any_ltr_tfbm_motif_enrichment, page_length = 15)",
    "```",
    "",
    "## RBP burden",
    "",
    "```{r rbp-burden-plot}",
    "plot_numeric(cmp$rbp_burden, 'RBP burden comparison', top_n = 10, padj_cutoff = 0.05)",
    "```",
    "",
    "```{r rbp-burden-table}",
    "safe_dt(cmp$rbp_burden, page_length = 10)",
    "```",
    "",
    "## RBP motif enrichment",
    "",
    "```{r rbp-motif-plot}",
    "plot_enrichment(cmp$rbp_motif_enrichment, 'RBP motif enrichment', top_n = top_n, padj_cutoff = 0.05)",
    "```",
    "",
    "```{r rbp-motif-table}",
    "safe_dt(cmp$rbp_motif_enrichment, page_length = 15)",
    "```",
    "",
    "# Output files",
    "",
    "```{r output-files}",
    "files <- list.files('.', recursive = TRUE)",
    "files <- files[grepl('\\\\.tsv$|\\\\.png$|\\\\.html$|\\\\.rds$', files)]",
    "safe_dt(data.frame(file = files), page_length = 20)",
    "```"
  )
  
  writeLines(rmd_text, rmd_file)
}


write_hervarium_annotation_dashboard_rmd <- function(rmd_file,
                                                     title,
                                                     top_n = 25,
                                                     self_contained = TRUE) {
  
  self_contained_txt <- ifelse(self_contained, "true", "false")
  
  rmd_text <- c(
    "---",
    paste0("title: \"", title, "\""),
    "output:",
    "  html_document:",
    "    toc: true",
    "    toc_float: true",
    "    theme: flatly",
    paste0("    self_contained: ", self_contained_txt),
    "---",
    "",
    "```{r setup, include=FALSE}",
    "knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)",
    "library(ggplot2)",
    "library(plotly)",
    "library(DT)",
    "",
    "anno <- readRDS('hervarium_dashboard_object.rds')",
    "features <- anno$features",
    "summary_table <- anno$summary",
    "stats <- anno$stats",
    "missing_ids <- anno$missing_ids",
    "top_n <- ", as.character(top_n),
    "",
    "domain_coverage_cutoff <- NA_real_",
    "",
    "if (!is.null(stats) &&",
    "    'domain_coverage_cutoff' %in% colnames(stats)) {",
    "  domain_coverage_cutoff <- stats$domain_coverage_cutoff[1]",
    "}",
    "",
    "domain_threshold_text <- ifelse(",
    "  is.na(domain_coverage_cutoff),",
    "  'No domain coverage threshold was found in the object. Domain summaries reflect the domain annotations stored in the input object.',",
    "  paste0(",
    "    'Internal retroviral domains were considered valid only when HMM profile coverage was >= ',",
    "    domain_coverage_cutoff,",
    "    '. Domain counts, domain-class presence, domain-type summaries and conservation plots are based on this threshold.'",
    "  )",
    ")",
    "",
    "safe_dt <- function(x, page_length = 10) {",
    "  if (is.null(x) || nrow(x) == 0) {",
    "    return(htmltools::HTML('<p><em>No results available for this section.</em></p>'))",
    "  }",
    "  DT::datatable(",
    "    x,",
    "    filter = 'top',",
    "    extensions = c('Buttons'),",
    "    options = list(",
    "      pageLength = page_length,",
    "      scrollX = TRUE,",
    "      dom = 'Bfrtip',",
    "      buttons = c('copy', 'csv', 'excel')",
    "    )",
    "  )",
    "}",
    "",
    "safe_plotly <- function(p) {",
    "  if (is.null(p)) return(NULL)",
    "  plotly::ggplotly(p)",
    "}",
    "",
    "has_cols <- function(df, cols) {",
    "  !is.null(df) && all(cols %in% colnames(df))",
    "}",
    "```",
    "",
    "# Overview",
    "",
    "## Analysis settings",
    "",
    "```{r analysis-settings}",
    "htmltools::div(",
    "  style = 'padding: 12px; border-left: 5px solid #0072B2; background-color: #F2F7FB; margin-bottom: 15px;',",
    "  htmltools::strong('Domain coverage threshold: '),",
    "  htmltools::HTML(domain_threshold_text)",
    ")",
    "```",
    "",
    "## Annotation statistics",
    "",
    "```{r stats}",
    "safe_dt(stats, page_length = 5)",
    "```",
    "",
    "## Compact HERV feature table",
    "",
    "```{r features}",
    "safe_dt(features, page_length = 15)",
    "```",
    "",
    "# Domain architecture",
    "",
    "## Domain count distribution",
    "",
    "```{r domain-count}",
    "if ('domain_count' %in% colnames(features)) {",
    "  p <- ggplot(features, aes(x = domain_count)) +",
    "    geom_histogram(binwidth = 1, boundary = -0.5) +",
    "    labs(title = 'Domain count distribution', x = 'Number of detected domains', y = 'Number of HERVs') +",
    "    theme_bw()",
    "  safe_plotly(p)",
    "}",
    "```",
    "",
    "## Maximum domain coverage distribution",
    "",
    "```{r coverage}",
    "if ('max_domain_cov' %in% colnames(features)) {",
    "  p <- ggplot(features, aes(x = max_domain_cov)) +",
    "    geom_histogram(bins = 30) +",
    "    labs(title = 'Maximum domain coverage distribution', x = 'Maximum HMM profile coverage', y = 'Number of HERVs') +",
    "    theme_bw()",
    "  safe_plotly(p)",
    "}",
    "```",
    "",
    "## Domain class presence",
    "",
    "```{r domain-class}",
    "domain_cols <- c('has_gag', 'has_pol', 'has_env', 'has_accessory')",
    "if (all(domain_cols %in% colnames(features))) {",
    "  domain_counts <- data.frame(",
    "    domain_class = c('gag', 'pol', 'env', 'accessory'),",
    "    n_hervs = c(",
    "      sum(features$has_gag, na.rm = TRUE),",
    "      sum(features$has_pol, na.rm = TRUE),",
    "      sum(features$has_env, na.rm = TRUE),",
    "      sum(features$has_accessory, na.rm = TRUE)",
    "    )",
    "  )",
    "  p <- ggplot(domain_counts, aes(x = reorder(domain_class, n_hervs), y = n_hervs)) +",
    "    geom_col() +",
    "    coord_flip() +",
    "    labs(title = 'Retroviral domain class presence', x = NULL, y = 'Number of HERVs') +",
    "    theme_bw()",
    "  safe_plotly(p)",
    "}",
    "```",
    "",
    "## Internal domain types",
    "",
    "```{r domain-types}",
    "parse_domain_types <- function(domains_type) {",
    "  if (is.na(domains_type) || domains_type == '' || domains_type == '.') return(character(0))",
    "  entries <- unlist(strsplit(as.character(domains_type), ';', fixed = TRUE))",
    "  entries <- entries[entries != '' & entries != '.']",
    "  domain_types <- vapply(entries, function(e) {",
    "    parts1 <- unlist(strsplit(e, '|', fixed = TRUE))",
    "    if (length(parts1) != 2) return(NA_character_)",
    "    parts2 <- unlist(strsplit(parts1[2], ':', fixed = TRUE))",
    "    if (length(parts2) != 2) return(NA_character_)",
    "    parts2[1]",
    "  }, character(1))",
    "  unique(domain_types[!is.na(domain_types)])",
    "}",
    "",
    "clean_domain_type <- function(z) {",
    "  z[z == 'ENV'] <- 'Env'",
    "  z[z == 'GAG'] <- 'Gag'",
    "  z[z == 'AP'] <- 'Protease'",
    "  z[z == 'DUT'] <- 'dUTPase'",
    "  z[z == 'INT'] <- 'Integrase'",
    "  z[z == 'RT'] <- 'RT'",
    "  z[z == 'RH'] <- 'RNaseH'",
    "  z",
    "}",
    "",
    "if ('domains_type' %in% colnames(features)) {",
    "  domain_type_long <- do.call(rbind, lapply(seq_len(nrow(features)), function(i) {",
    "    dt <- parse_domain_types(features$domains_type[i])",
    "    if (length(dt) == 0) return(NULL)",
    "    data.frame(HERV_id = features$HERV_id[i], domain_type = clean_domain_type(dt))",
    "  }))",
    "  if (!is.null(domain_type_long) && nrow(domain_type_long) > 0) {",
    "    domain_type_long <- unique(domain_type_long)",
    "    domain_type_counts <- as.data.frame(table(domain_type_long$domain_type))",
    "    colnames(domain_type_counts) <- c('domain_type', 'n_hervs')",
    "    domain_type_counts <- domain_type_counts[order(domain_type_counts$n_hervs, decreasing = TRUE), ]",
    "    p <- ggplot(head(domain_type_counts, top_n), aes(x = reorder(domain_type, n_hervs), y = n_hervs)) +",
    "      geom_col() +",
    "      coord_flip() +",
    "      labs(title = 'Specific internal domain type presence', x = NULL, y = 'Number of HERVs') +",
    "      theme_bw()",
    "    safe_plotly(p)",
    "  }",
    "}",
    "```",
    "",
    "# HERV identity and genomic context",
    "",
    "## Top subfamilies",
    "",
    "```{r subfamilies}",
    "if ('subfamily' %in% colnames(features)) {",
    "  sub_counts <- as.data.frame(table(features$subfamily))",
    "  colnames(sub_counts) <- c('subfamily', 'n')",
    "  sub_counts <- sub_counts[order(sub_counts$n, decreasing = TRUE), ]",
    "  sub_counts <- head(sub_counts, top_n)",
    "  p <- ggplot(sub_counts, aes(x = reorder(subfamily, n), y = n)) +",
    "    geom_col() +",
    "    coord_flip() +",
    "    labs(title = 'Top HERV subfamilies', x = NULL, y = 'Number of HERVs') +",
    "    theme_bw()",
    "  safe_plotly(p)",
    "}",
    "```",
    "",
    "## Genomic/transcriptomic context",
    "",
    "```{r context}",
    "context_cols <- c('is_intergenic', 'overlaps_exon', 'overlaps_intron', 'overlaps_cds', 'overlaps_utr', 'overlaps_lncRNA', 'overlaps_protein_coding')",
    "context_cols <- context_cols[context_cols %in% colnames(features)]",
    "if (length(context_cols) > 0) {",
    "  context_counts <- data.frame(",
    "    context = context_cols,",
    "    n_hervs = vapply(context_cols, function(z) sum(features[[z]], na.rm = TRUE), numeric(1))",
    "  )",
    "  p <- ggplot(context_counts, aes(x = reorder(context, n_hervs), y = n_hervs)) +",
    "    geom_col() +",
    "    coord_flip() +",
    "    labs(title = 'Genomic/transcriptomic context', x = NULL, y = 'Number of HERVs') +",
    "    theme_bw()",
    "  safe_plotly(p)",
    "}",
    "```",
    "",
    "# Regulatory layers",
    "",
    "## LTR TFBM burden from backbone annotation",
    "",
    "```{r ltr-tfbm-burden}",
    "burden_cols <- c('ltr5_tfbm_burden', 'ltr3_tfbm_burden', 'total_ltr_tfbm_burden')",
    "burden_cols <- burden_cols[burden_cols %in% colnames(features)]",
    "if (length(burden_cols) > 0) {",
    "  burden_long <- do.call(rbind, lapply(burden_cols, function(col) {",
    "    data.frame(layer = col, burden = suppressWarnings(as.numeric(features[[col]])))",
    "  }))",
    "  p <- ggplot(burden_long, aes(x = burden)) +",
    "    geom_histogram(bins = 30) +",
    "    facet_wrap(~ layer, scales = 'free_x') +",
    "    labs(title = 'LTR TFBM burden distributions', x = 'TFBM burden', y = 'Number of HERVs') +",
    "    theme_bw()",
    "  safe_plotly(p)",
    "}",
    "```",
    "",
    "## IFN-related LTR motif features",
    "",
    "```{r ifn-ltr}",
    "ifn_cols <- c(",
    "  'has_any_ifn_related_ltr_motif',",
    "  'has_any_stat1_motif',",
    "  'has_any_stat1stat2_motif',",
    "  'has_ltr5_stat1_motif',",
    "  'has_ltr3_stat1_motif',",
    "  'has_ltr5_stat1stat2_motif',",
    "  'has_ltr3_stat1stat2_motif'",
    ")",
    "ifn_cols <- ifn_cols[ifn_cols %in% colnames(features)]",
    "if (length(ifn_cols) > 0) {",
    "  ifn_counts <- data.frame(",
    "    feature = ifn_cols,",
    "    n_hervs = vapply(ifn_cols, function(z) sum(features[[z]], na.rm = TRUE), numeric(1))",
    "  )",
    "  p <- ggplot(ifn_counts, aes(x = reorder(feature, n_hervs), y = n_hervs)) +",
    "    geom_col() +",
    "    coord_flip() +",
    "    labs(title = 'IFN-related LTR motif summary', x = NULL, y = 'Number of HERVs') +",
    "    theme_bw()",
    "  safe_plotly(p)",
    "}",
    "```",
    "",
    "## Detailed LTR TFBM hits: combined LTRs",
    "",
    "```{r detailed-ltr-tfbm-hits-combined}",
    "if (!is.null(anno$ltr_tfbm_hits) && nrow(anno$ltr_tfbm_hits) > 0) {",
    "  tfbm_hits <- anno$ltr_tfbm_hits",
    "  motif_counts <- as.data.frame(table(tfbm_hits$motif_alt_id))",
    "  colnames(motif_counts) <- c('motif_alt_id', 'n_hits')",
    "  motif_counts <- motif_counts[order(motif_counts$n_hits, decreasing = TRUE), ]",
    "  p <- ggplot(head(motif_counts, top_n), aes(x = reorder(motif_alt_id, n_hits), y = n_hits)) +",
    "    geom_col() +",
    "    coord_flip() +",
    "    labs(title = 'Top detailed LTR TFBM motifs: combined LTRs', x = NULL, y = 'Number of motif hits') +",
    "    theme_bw()",
    "  safe_plotly(p)",
    "} else {",
    "  htmltools::HTML('<p><em>No detailed LTR TFBM hits found. Run profile_hervs(..., add_tfbm_details = TRUE, fimo_file = ...) to enable this section.</em></p>')",
    "}",
    "```",
    "",
    "## Detailed LTR TFBM hits: 5' LTR",
    "",
    "```{r detailed-ltr5-tfbm-hits}",
    "if (!is.null(anno$ltr_tfbm_hits) && nrow(anno$ltr_tfbm_hits) > 0 && 'ltr_position' %in% colnames(anno$ltr_tfbm_hits)) {",
    "  tfbm_hits_ltr5 <- anno$ltr_tfbm_hits[anno$ltr_tfbm_hits$ltr_position == 'LTR5', ]",
    "  if (nrow(tfbm_hits_ltr5) > 0) {",
    "    motif_counts <- as.data.frame(table(tfbm_hits_ltr5$motif_alt_id))",
    "    colnames(motif_counts) <- c('motif_alt_id', 'n_hits')",
    "    motif_counts <- motif_counts[order(motif_counts$n_hits, decreasing = TRUE), ]",
    "    p <- ggplot(head(motif_counts, top_n), aes(x = reorder(motif_alt_id, n_hits), y = n_hits)) +",
    "      geom_col() +",
    "      coord_flip() +",
    "      labs(title = 'Top detailed TFBM motifs in 5' LTRs', x = NULL, y = 'Number of motif hits') +",
    "      theme_bw()",
    "    safe_plotly(p)",
    "  } else {",
    "    htmltools::HTML('<p><em>No detailed TFBM hits found in 5' LTRs.</em></p>')",
    "  }",
    "} else {",
    "  htmltools::HTML('<p><em>No detailed LTR TFBM hits with LTR position information found.</em></p>')",
    "}",
    "```",
    "",
    "## Detailed LTR TFBM hits: 3' LTR",
    "",
    "```{r detailed-ltr3-tfbm-hits}",
    "if (!is.null(anno$ltr_tfbm_hits) && nrow(anno$ltr_tfbm_hits) > 0 && 'ltr_position' %in% colnames(anno$ltr_tfbm_hits)) {",
    "  tfbm_hits_ltr3 <- anno$ltr_tfbm_hits[anno$ltr_tfbm_hits$ltr_position == 'LTR3', ]",
    "  if (nrow(tfbm_hits_ltr3) > 0) {",
    "    motif_counts <- as.data.frame(table(tfbm_hits_ltr3$motif_alt_id))",
    "    colnames(motif_counts) <- c('motif_alt_id', 'n_hits')",
    "    motif_counts <- motif_counts[order(motif_counts$n_hits, decreasing = TRUE), ]",
    "    p <- ggplot(head(motif_counts, top_n), aes(x = reorder(motif_alt_id, n_hits), y = n_hits)) +",
    "      geom_col() +",
    "      coord_flip() +",
    "      labs(title = 'Top detailed TFBM motifs in 3' LTRs', x = NULL, y = 'Number of motif hits') +",
    "      theme_bw()",
    "    safe_plotly(p)",
    "  } else {",
    "    htmltools::HTML('<p><em>No detailed TFBM hits found in 3' LTRs.</em></p>')",
    "  }",
    "} else {",
    "  htmltools::HTML('<p><em>No detailed LTR TFBM hits with LTR position information found.</em></p>')",
    "}",
    "```",
    "",
    "## Detailed LTR TFBM summary table",
    "",
    "```{r detailed-ltr-tfbm-table}",
    "if (!is.null(anno$herv_tfbm_summary) && nrow(anno$herv_tfbm_summary) > 0) {",
    "  safe_dt(anno$herv_tfbm_summary, page_length = 15)",
    "}",
    "```",
    "",
    "## Raw detailed LTR TFBM hits table",
    "",
    "```{r raw-detailed-ltr-tfbm-hits-table}",
    "if (!is.null(anno$ltr_tfbm_hits) && nrow(anno$ltr_tfbm_hits) > 0) {",
    "  safe_dt(anno$ltr_tfbm_hits, page_length = 15)",
    "}",
    "```",
    "## RBP burden from backbone annotation",
    "",
    "```{r rbp-burden}",
    "rbp_cols <- c('rbp_burden', 'rbp_unique')",
    "rbp_cols <- rbp_cols[rbp_cols %in% colnames(features)]",
    "if (length(rbp_cols) > 0) {",
    "  rbp_long <- do.call(rbind, lapply(rbp_cols, function(col) {",
    "    data.frame(layer = col, value = suppressWarnings(as.numeric(features[[col]])))",
    "  }))",
    "  p <- ggplot(rbp_long, aes(x = value)) +",
    "    geom_histogram(bins = 30) +",
    "    facet_wrap(~ layer, scales = 'free_x') +",
    "    labs(title = 'RBP burden distributions', x = 'RBP metric', y = 'Number of HERVs') +",
    "    theme_bw()",
    "  safe_plotly(p)",
    "}",
    "```",
    "",
    "## Detailed RBP motif hits",
    "",
    "```{r detailed-rbp-hits}",
    "if (!is.null(anno$rbp_hits) && nrow(anno$rbp_hits) > 0) {",
    "  rbp_hits <- anno$rbp_hits",
    "  rbp_counts <- as.data.frame(table(rbp_hits$motif_alt_id))",
    "  colnames(rbp_counts) <- c('rbp_motif', 'n_hits')",
    "  rbp_counts <- rbp_counts[order(rbp_counts$n_hits, decreasing = TRUE), ]",
    "  p <- ggplot(head(rbp_counts, top_n), aes(x = reorder(rbp_motif, n_hits), y = n_hits)) +",
    "    geom_col() +",
    "    coord_flip() +",
    "    labs(title = 'Top detailed RBP motifs', x = NULL, y = 'Number of motif hits') +",
    "    theme_bw()",
    "  safe_plotly(p)",
    "} else {",
    "  htmltools::HTML('<p><em>No detailed RBP hits found. Run add_rbp_details() before generating the report, or use profile_hervs() once add_rbp_details is integrated there.</em></p>')",
    "}",
    "```",
    "",
    "```{r detailed-rbp-table}",
    "if (!is.null(anno$herv_rbp_summary) && nrow(anno$herv_rbp_summary) > 0) {",
    "  safe_dt(anno$herv_rbp_summary, page_length = 15)",
    "}",
    "```",
    "",
    "# Full tables",
    "",
    "## Full annotation table",
    "",
    "```{r summary-table}",
    "safe_dt(summary_table, page_length = 15)",
    "```",
    "",
    "## Missing IDs",
    "",
    "```{r missing}",
    "safe_dt(data.frame(missing_id = missing_ids), page_length = 10)",
    "```",
    "",
    "# Output files",
    "",
    "```{r output-files}",
    "files <- list.files('.', recursive = TRUE)",
    "files <- files[grepl('\\\\.tsv$|\\\\.png$|\\\\.html$|\\\\.rds$', files)]",
    "safe_dt(data.frame(file = files), page_length = 20)",
    "```"
  )
  
  writeLines(rmd_text, rmd_file)
}